# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20170222_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 10, 52, 18, 526274, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 10, 52, 18, 523459, tzinfo=utc)),
        ),
    ]
