# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_auto_20170222_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 10, 56, 19, 56052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 10, 56, 19, 53184, tzinfo=utc)),
        ),
    ]
