# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0008_auto_20170222_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 11, 27, 9, 24108, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 11, 27, 9, 21754, tzinfo=utc)),
        ),
    ]
