# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 11:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0009_auto_20170222_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 11, 34, 15, 388956, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 11, 34, 15, 387542, tzinfo=utc)),
        ),
    ]
