# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 13:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0021_auto_20170223_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 24, 13, 8, 41, 419813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 24, 13, 8, 41, 417860, tzinfo=utc)),
        ),
    ]
