# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_subscription_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Frank', max_length=35)),
                ('last_name', models.CharField(default='Test', max_length=35)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='number_family',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='family',
            name='account_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
