# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170223_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_family',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Number of Family Members'),
        ),
    ]
