# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170223_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Frank', max_length=35)),
                ('last_name', models.CharField(default='Test', max_length=35)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_10',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_6',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_7',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_8',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_9',
        ),
        migrations.AddField(
            model_name='family',
            name='account_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
