# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170223_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='family',
            name='last_name',
        ),
        migrations.AddField(
            model_name='family',
            name='full_name',
            field=models.CharField(default='', max_length=35),
        ),
    ]
