# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170223_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_family',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, verbose_name='Number of family members (including you)'),
        ),
    ]
