# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Family'),
        ),
    ]
