# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 10:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20170219_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 19, 10, 53, 40, 159392, tzinfo=utc)),
        ),
    ]
