# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20170220_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 20, 18, 19, 45, 596335, tzinfo=utc)),
        ),
    ]
